Feature('Lib')

Scenario('should have class "jedi-ready" when ready @ready', ({ I }) => {
  I.amOnPage('index.html')
  I.waitForElement('.jedi-ready')
})

Scenario('should destroy', ({ I }) => {
  I.amOnPage('index.html')
  I.waitForElement('.jedi-ready')
  I.seeElement('[data-schemapath="root"]')
  I.click('destroy')
  I.dontSeeElement('[data-schemapath="root"]')
})

Scenario('Should create all kind of editors', ({ I }) => {
  I.amOnPage('index.html')
  I.waitForElement('.jedi-ready')
  I.waitForText('Editors', 'h3')
  I.waitForElement('[data-path="root"]')
  I.waitForElement('[data-path="root.booleans"]')
  I.waitForElement('[data-path="root.booleans.boolean"]')
  I.waitForElement('[data-path="root.booleans.boolean-enum"]')
  I.waitForElement('[data-path="root.booleans.boolean-enum-radio"]')
  I.waitForElement('[data-path="root.strings"]')
  I.waitForElement('[data-path="root.strings.string"]')
  I.waitForElement('[data-path="root.strings.string-textarea"]')
  I.waitForElement('[data-path="root.strings.string-enum-select"]')
  I.waitForElement('[data-path="root.strings.string-enum-radio"]')
  I.waitForElement('[data-path="root.numbers"]')
  I.waitForElement('[data-path="root.numbers.number"]')
  I.waitForElement('[data-path="root.numbers.number-enum-select"]')
  I.waitForElement('[data-path="root.numbers.number-enum-radio"]')
  I.waitForElement('[data-path="root.integers"]')
  I.waitForElement('[data-path="root.integers.integer"]')
  I.waitForElement('[data-path="root.integers.integer-enum-select"]')
  I.waitForElement('[data-path="root.integers.integer-enum-radio"]')
  I.waitForElement('[data-path="root.arrays"]')
  I.waitForElement('[data-path="root.arrays.string-array"]')
  I.waitForElement('[data-path="root.multiple"]')
  I.waitForElement('[data-path="root.multiple.oneof"]')
  I.waitForElement('[data-path="root.multiple.anyof"]')
  I.waitForElement('[data-path="root.multiple.type-array"]')
  I.waitForElement('[data-path="root.multiple.type-undefined"]')
  I.waitForElement('[data-path="root.multiple.type-any"]')
})
