/* global Feature Scenario */
const jsonData = require('./test')

Feature('Lib')

Scenario('should have class "jedi-ready" when ready @ready', ({ I }) => {
  I.amOnPage('index.html')
  I.click('[href="#schema-tab"]')
  I.fillField('#schemas', 'All editors')
  I.waitForElement('.jedi-ready')
})

Scenario('Should create all kind of editors', ({ I }) => {
  I.amOnPage('index.html')
  I.click('[href="#schema-tab"]')
  I.fillField('#schemas', 'All editors')
  I.waitForElement('.jedi-ready')
  I.waitForText('Editor', 'h3')
  I.waitForElement('[data-path="root"]')
  I.waitForElement('[data-path="root.booleans"]')
  I.waitForElement('[data-path="root.booleans.boolean"]')
  I.waitForElement('[data-path="root.booleans.boolean-enum-select"]')
  I.waitForElement('[data-path="root.booleans.boolean-enum-radio"]')
  I.waitForElement('[data-path="root.strings"]')
  I.waitForElement('[data-path="root.strings.string"]')
  I.waitForElement('[data-path="root.strings.string-textarea"]')
  I.waitForElement('[data-path="root.strings.string-enum-select"]')
  I.waitForElement('[data-path="root.strings.string-enum-radio"]')
  I.waitForElement('[data-path="root.numbers"]')
  I.waitForElement('[data-path="root.numbers.number"]')
  I.waitForElement('[data-path="root.numbers.number-enum-select"]')
  I.waitForElement('[data-path="root.numbers.number-enum-radio"]')
  I.waitForElement('[data-path="root.integers"]')
  I.waitForElement('[data-path="root.integers.integer"]')
  I.waitForElement('[data-path="root.integers.integer-enum-select"]')
  I.waitForElement('[data-path="root.integers.integer-enum-radio"]')
  I.waitForElement('[data-path="root.arrays"]')
  I.waitForElement('[data-path="root.arrays.string-array"]')
  I.waitForElement('[data-path="root.multiple"]')
  I.waitForElement('[data-path="root.multiple.oneof"]')
  I.waitForElement('[data-path="root.multiple.anyof"]')
  I.waitForElement('[data-path="root.multiple.type-array"]')
  I.waitForElement('[data-path="root.multiple.type-undefined"]')
  I.waitForElement('[data-path="root.multiple.type-any"]')
})

Scenario('should destroy', ({ I }) => {
  I.amOnPage('index.html')
  I.click('[href="#schema-tab"]')
  I.fillField('#schemas', 'All editors')
  I.waitForElement('.jedi-ready')
  I.click('[href="#actions-tab"]')
  I.waitForElement('#destroy-editor')
  I.click('#destroy-editor')
  I.dontSeeElement('[data-schemapath="root"]')
})

Scenario('Should disable and enable', ({ I }) => {
  I.amOnPage('index.html')
  I.click('[href="#schema-tab"]')
  I.fillField('#schemas', 'All editors')
  I.waitForElement('.jedi-ready')
  I.click('[href="#actions-tab"]')
  I.waitForElement('#disable-editor')
  I.click('#disable-editor')
  I.dontSeeElement('.jedi-ready input:not(:disabled)')
  I.dontSeeElement('.jedi-ready textarea:not(:disabled)')
  I.dontSeeElement('.jedi-ready select:not(:disabled)')
  I.dontSeeElement('.jedi-ready button:not(:disabled)')
  I.click('#enable-editor')
  I.dontSeeElement('.jedi-ready input[disabled]')
  I.dontSeeElement('.jedi-ready textarea[disabled]')
  I.dontSeeElement('.jedi-ready select[disabled]')
  I.dontSeeElement('.jedi-ready button[disabled]')
})

Scenario('should set value', async ({ I }) => {
  I.amOnPage('index.html')
  I.click('[href="#schema-tab"]')
  I.fillField('#schemas', 'All editors')
  I.waitForElement('.jedi-ready')
  I.click('[href="#value-tab"]')
  I.click('#editor-value')
  I.fillField('#editor-value', JSON.stringify(jsonData))
  I.click('#set-value')
  I.wait(1)
  I.waitForValue('[id="jedi-hidden-input"]', JSON.stringify(jsonData))
  I.seeCheckboxIsChecked('[id="root.booleans.boolean"]')
  I.seeInField('[id="root.booleans.boolean-enum-select"]', 'true')
  I.seeInField('[id="root.booleans.boolean-enum-radio.1"]', 'true')
  I.seeInField('[id="root.strings.string"]', 'carl')
  I.seeInField('[id="root.strings.string-textarea"]', 'carl')
  I.seeInField('[id="root.strings.string-enum-select"]', 'carl')
  I.seeInField('[id="root.strings.string-enum-radio.2"]', 'carl')
  I.seeInField('[id="root.numbers.number"]', 3.5)
  I.seeInField('[id="root.numbers.number-enum-select"]', '3.5')
  I.seeInField('[id="root.numbers.number-enum-radio.2"]', '3.5')
  I.seeInField('[id="root.integers.integer"]', 3)
  I.seeInField('[id="root.integers.integer-enum-select"]', '3')
  I.seeInField('[id="root.integers.integer-enum-radio.2"]', '3')
})
