---
type: object
title: Editors
required:
  - multiple
  - booleans
  - strings
  - numbers
  - integers
  - arrays
properties:
  multiple:
    type: object
    title: Multiple
    properties:
      oneof:
        oneOf:
          - type: boolean
            title: boolean
          - type: string
            title: string
          - type: integer
            title: integer
      anyof:
        title: anyOf
        anyOf:
          - type: boolean
            title: anyOf boolean
          - type: boolean
            title: anyOf boolean enum select
            format: select
            options:
              enumTitles:
                - 'No'
                - 'Yes'
          - type: boolean
            title: boolean enum radio
            format: radio
            options:
              enumTitles:
                - 'No'
                - 'Yes'
      type-array:
        type:
          - string
          - boolean
        title: type array
      type-undefined:
        title: type undefined
      type-any:
        type: any
        title: 'type: any'
  booleans:
    type: object
    required:
      - boolean
      - boolean-enum
      - boolean-enum-radio
    title: Booleans
    properties:
      boolean:
        type: boolean
        title: boolean
      boolean-enum:
        type: boolean
        title: boolean enum select
        format: select
        options:
          enumTitles:
            - 'No'
            - 'Yes'
      boolean-enum-radio:
        type: boolean
        title: boolean enum radio
        format: radio
        options:
          enumTitles:
            - 'No'
            - 'Yes'
  strings:
    type: object
    title: Strings
    required:
      - string
      - string-textarea
      - string-enum-select
      - string-enum-radio
    properties:
      string:
        type: string
        title: string
      string-textarea:
        type: string
        format: textarea
        title: string textarea
        minLength: 3
      string-enum-select:
        type: string
        title: string enum select
        enum:
          - albert
          - betti
          - carl
        options:
          enumTitles:
            - Albert
            - Betti
            - Carl
      string-enum-radio:
        type: string
        title: string enum radio
        format: radio
        enum:
          - albert
          - betti
          - carl
        options:
          enumTitles:
            - Albert
            - Betti
            - Carl
  numbers:
    type: object
    title: Numbers
    required:
      - number
      - number-enum-select
      - number-enum-radio
    properties:
      number:
        type: number
        title: number
      number-enum-select:
        type: number
        title: number enum select
        enum:
          - 1.5
          - 2.5
          - 3.5
        options:
          enumTitles:
            - small (1.5)
            - medium (2.5)
            - big (3.5)
      number-enum-radio:
        type: number
        title: number enum radio
        format: radio
        enum:
          - 1.5
          - 2.5
          - 3.5
        options:
          enumTitles:
            - small (1.5)
            - medium (2.5)
            - big (3.5)
  integers:
    type: object
    title: Integers
    required:
      - integer
      - integer-enum-select
      - integer-enum-radio
    properties:
      integer:
        type: integer
        title: integer
      integer-enum-select:
        type: integer
        title: integer enum select
        enum:
          - 1
          - 2
          - 3
        options:
          enumTitles:
            - small (1)
            - medium (2)
            - big (3)
      integer-enum-radio:
        type: number
        title: integer enum radio
        format: radio
        enum:
          - 1
          - 2
          - 3
        options:
          enumTitles:
            - small (1)
            - medium (2)
            - big (3)
  arrays:
    type: object
    title: Arrays
    required:
      - string-array
    properties:
      string-array:
        type: array
        title: strings color
        items:
          type: string
          title: color
          format: color
        default:
          - "#b02727"
          - "#226996"
