/* global Feature Scenario */
const theme = process.env.THEME || 'wireframe'

Feature('maximum')

Scenario('should display maximum validation errors @maximum', ({ I }) => {
  I.amOnPage('index.html')
  I.fillField('#theme', theme)
  I.waitForElement('.jedi-ready')
  I.fillField('#schemas', 'validators/maximum')
  I.waitForElement('.jedi-ready')
  I.dontSee('number_maximum must be less than 100', '[data-path="root.number_maximum"]')
  I.dontSee('number_exclusive_maximum must be less than 99', '[data-path="root.number_exclusive_maximum"]')
  I.dontSee('integer_maximum must be less than 100', '[data-path="root.integer_maximum"]')
  I.dontSee('integer_exclusive_maximum must be less than 99', '[data-path="root.integer_exclusive_maximum"]')
  I.fillField('[id="root.number_maximum"]', 101)
  I.pressKey('Tab')
  I.fillField('[id="root.number_exclusive_maximum"]', 100)
  I.pressKey('Tab')
  I.fillField('[id="root.integer_maximum"]', 101)
  I.pressKey('Tab')
  I.fillField('[id="root.integer_exclusive_maximum"]', 100)
  I.pressKey('Tab')
  I.waitForText('number_maximum must be less than 100', '[data-path="root.number_maximum"]')
  I.waitForText('number_exclusive_maximum must be less than 99', '[data-path="root.number_exclusive_maximum"]')
  I.waitForText('integer_maximum must be less than 100', '[data-path="root.integer_maximum"]')
  I.waitForText('integer_exclusive_maximum must be less than 99', '[data-path="root.integer_exclusive_maximum"]')
  I.fillField('[id="root.number_maximum"]', 100)
  I.pressKey('Tab')
  I.fillField('[id="root.number_exclusive_maximum"]', 99)
  I.pressKey('Tab')
  I.fillField('[id="root.integer_maximum"]', 100)
  I.pressKey('Tab')
  I.fillField('[id="root.integer_exclusive_maximum"]', 99)
  I.pressKey('Tab')
  I.dontSee('number_maximum must be less than 100', '[data-path="root.number_maximum"]')
  I.dontSee('number_exclusive_maximum must be less than 99', '[data-path="root.number_exclusive_maximum"]')
  I.dontSee('integer_maximum must be less than 100', '[data-path="root.integer_maximum"]')
  I.dontSee('integer_exclusive_maximum must be less than 99', '[data-path="root.integer_exclusive_maximum"]')
})
