name: Tests
on: [push, pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn unit
  e2e-barebones:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn serve & yarn e2e
  e2e-bootstrap-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn serve & yarn e2e:b3
  e2e-bootstrap-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn serve & yarn e2e:b4
  e2e-bootstrap-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn serve & yarn e2e:b5