name: Tests
on: [push, pull_request]
jobs:
  unit:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn unit
  e2e:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        run: node -v
      - name: Install
        run: yarn install
      - name: Test
        run: yarn e2e:b3